name: DevSecOps Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-security:
    name: Build & Security Scans
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout del código
        uses: actions/checkout@v4

      - name: 2. Setup de Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: 3. Compilación (CI)
        run: mvn clean package -DskipTests

      - name: 4. SAST - Escaneo con Semgrep mediante Docker
        run: |
          docker run --rm -v "${{ github.workspace }}:/src" returntocorp/semgrep semgrep scan --config auto --json --output semgrep-report.json || true

      - name: 5. Construir Imagen Docker del Proyecto
        run: docker build -t spring-boot-webapi:latest .

      - name: 6. Escaneo de Imagen - Trivy Action
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'spring-boot-webapi:latest'
          format: 'json'
          output: 'trivy-report.json'
          exit-code: '0'

      - name: 7. Publicar Reportes (Artifacts)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: |
            semgrep-report.json
            trivy-report.json